version: '3'
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    command: bash -c "bundle exec rails s -p 3000 -b 0.0.0.0"
    volumes:
      - ./:/app
      - bundler_data:/usr/local/bundle
    ports:
      - "3000:3000"
    links:
      - mysql
    stdin_open: true
    tty: true
  mysql:
    image: mysql:8.0.3
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
volumes:
  mysql_data:
  bundler_data:
